# Generated by Django 5.2.7 on 2025-11-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditwallet',
            name='balance',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
