# Generated by Django 5.2.7 on 2025-11-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact number for real-time communication', max_length=20),
        ),
    ]
