# Generated by Django 5.2.7 on 2025-11-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.CharField(choices=[('60', '60 minutes'), ('90', '90 minutes'), ('120', '2 hours')], default='60', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='When the session is scheduled', null=True),
        ),
    ]
