# Generated by Django 5.2.9 on 2025-12-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('biomedical', 'Bio Medical'), ('commerce', 'Commerce and Finance'), ('fine_arts', 'Fine Arts'), ('computer_science', 'Computer Science'), ('mathematics', 'Mathematics and Statistics'), ('physics', 'Physics and Astronomy'), ('chemistry', 'Chemistry'), ('biological', 'Biological Sciences'), ('law', 'Law'), ('psychology', 'Psychology'), ('history', 'History'), ('politics', 'Politics and International Relations'), ('english', 'English Language and Literature'), ('medicine', 'Medicine'), ('nursing', 'Nursing and Midwifery'), ('architecture', 'Architecture'), ('education', 'Education'), ('other', 'Other')], default='other', help_text='Your academic department', max_length=50),
        ),
    ]
